### PR TITLE
Add support for rolling back hasMany relationships

### PR DESCRIPTION
**Pull request by royk**
I've tested this functionality with a project I'm working on. At the very least the existing belongsTo rollback functionality shouldn't be affected

### CODE REVIEW

**Comment by dylanmensaert** [comment]
Regarding your comment, it is unclear what you mean.

Can you state your exact problem with related code or logical behaviour? Thanks!

**Comment by royk** [comment]
hasMany rollback doesn't happens natively for me, so this pull request adds that functionality.
Let's say you have a model:

user: {
 posts: hasMany('post')
}

and you add a post to the user

With the functionality added to the pull request, after rollback the added post will be removed from the relationship. Without the above pull request, the added post will remain.

**Comment by dylanmensaert** [comment]
`hasMany` relationships are just references, the actual data you would like to rollback are the **Posts**, since they hold the actual data referencing the **User**.

I created a Twiddle to show `hasMany` being updated automatically by Ember-Data when changing the `belongsTo`:
https://ember-twiddle.com/a62845d00f205751d35dd951b5b98c1b?openFiles=templates.application.hbs%2C

Your suggestion holds `hasMany` references on a separate hash, which is unnecessary, hence the tons of extra code you had to write. `hasMany` is and should stay a computation of inverse `belongsTo` initializations.

I suggest caching your initial `initPosts = user.get('posts').toArray()` and rolling back later:
```
initPosts.pushObjects(user.get('posts'));

initPosts.forEach(function(post) {
  post.rollbackAttributes();
});
```
I could implement an option to provide this somehow but I like to keep things simple so I will not merge the pull request.

Feel free to post any disagreements if you would like to discuss :)

**Comment by dylanmensaert** [comment]
Functionality available in [v1.2.2](https://github.com/dylanmensaert/ember-rollback-relationships/releases/tag/1.2.2)

**Pull request closed without merging**
